source 'https://rubygems.org'
gem 'rails', '4.0.4'
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'mongoid', github: 'mongoid/mongoid'
gem 'bson_ext'
gem 'gl-matrix-rails'

gem 'slim-rails'
gem 'inherited_resources'
